name = "windsurf-worker"
main = "workers/index.ts"
compatibility_date = "2023-12-01"

# Worker configuration
[build]
command = "pnpm install && pnpm run build"
watch_dir = "workers"

[dev]
port = 8787

[vars]
# Environment variables are now managed through Cloudflare Dashboard
# or through .dev.vars file locally

# Pages configuration
[site]
bucket = "./build"  # React build output directory

[env.development]
vars = { }
